# site settings
title: Unidad de Datos
subtitle: Repositorio de Base de datos
email: udata@aru.org.bo
description: Banco de Datos
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://biam2.github.io" 
author: Unidad de Datos
street_address: Arce
city: La Paz
state: La Paz
zip_code: NA
country: Bolivia
phone: (+591) 22004492

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
#github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
