url: https://alfabetizacion-estadistica-bolivia.github.io/
baseurl: https://biam2.github.io/
# Site settings
title: Alfabetización Bia
email: mailto:bmamani@aru.org.bo
description: " "


# Team names, titles and social links
people:
- name: Instituto Nacional de Estadística
  pic: ine
  position: Lead Designer
  social:
    - title: twitter
      url: https://twitter.com/ineoficialbo?lang=es
    - title: facebook
      url: https://www.facebook.com/ineboliviaoficial/

- name: Carrera de Estadística - UMSA
  pic: stat
  position: Lead Marketer
  social:
    - title: facebook
      url: https://www.facebook.com/Carrera-de-Estad%C3%ADstica-UMSA-1268600956524094/
    - title: google-plus
      url: http://www.universia.com.bo/estudios/umsa/estadistica/st/177521

- name: Fundación Aru
  pic: arulogo
  position: Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/arufoundation?lang=es
    - title: facebook
      url: https://www.facebook.com/FundacionARU
    - title: google-plus
      url: https://www.aru.org.bo/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty